name: Metrics
on:
  # Schedule updates (each day at 00:00)
  schedule: [{cron: "00 00 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: BramVanPevenage
          filename: github-metrics-bram_van_pevenage.svg
          template: classic
          base: header, activity, community, repositories, metadata
          repositories-forks: no
          repositories_affiliations: owner, organization_member, collaborator
          config_timezone: Europe/Brussels
          plugin_introduction: no
          plugin_introduction_title: no
          plugin_isocalendar: no
          plugin_isocalendar_duration: half-year
          # Language Metrics
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_threshold: 0%
          plugin_languages_limit: 5
          plugin_languages_details: percentage, lines
          # Achiefments plugin
          plugin_achievements: yes
          # Issue tracker plugin
          plugin_followup: yes
          plugin_followup_sections: repository, user
          #lines
          plugin_lines: yes
          plugin_stackoverflow: no
          plugin_stackoverflow_limit: 2
          plugin_stackoverflow_lines: 4
          plugin_stackoverflow_sections: answers-top, questions-recent
          plugin_stackoverflow_user: 13221494
          plugin_stargazers: no
          plugin_habits: no
          plugin_habits_from: 200       # Use 200 events to compute habits
          plugin_habits_days: 14        # Keep only events from last 14 days
          plugin_habits_facts: yes      # Display facts section
          plugin_habits_charts: yes     # Display charts section
          plugin_reactions: no
          plugin_reactions_limit: 200                 # Compute reactions over last 200 issue comments
          plugin_reactions_days: 14                   # Compute reactions on issue comments posted less than 14 days ago
          plugin_reactions_details: count, percentage # Display reactions count and percentage
